# Introduction to NumPy

---

##  Theory

NumPy (Numerical Python) is a powerful open-source Python library used for numerical computing.  
It provides support for:
- Multidimensional arrays (ndarray)
- Mathematical operations on arrays
- Linear algebra, Fourier transforms, random number generation

NumPy is faster than regular Python lists because it uses optimized **C libraries** internally.  
It is the foundation for many data science and machine learning libraries such as **Pandas, TensorFlow, SciPy, and Scikit-learn**.

---


##  Applications

- Handling large multidimensional arrays and matrices.
- Performing mathematical and statistical operations efficiently.
- Data preprocessing in Machine Learning.
- Basis for scientific computing libraries.
- Used in image processing, signal processing, and simulations.
- Vectorization (eliminating loops, improving performance).

## 3. List of Functions and Their Usage

Some important NumPy functions:

| Function | Usage |
|----------|--------|
| `np.array()` | Create an array |
| `np.arange(start, stop, step)` | Create array with range of values |
| `np.zeros((m,n))` | Create array filled with zeros |
| `np.ones((m,n))` | Create array filled with ones |
| `np.eye(n)` | Identity matrix |
| `np.linspace(start, stop, num)` | Create evenly spaced numbers |
| `np.random.rand(m,n)` | Random numbers between 0 and 1 |
| `np.shape` | Get dimensions of array |
| `np.reshape()` | Reshape array |
| `np.sum(), np.mean(), np.std()` | Aggregation functions |
| `np.min(), np.max(), np.argmin(), np.argmax()` | Min/Max values & indices |
| `np.dot(), np.matmul()` | Matrix multiplication |
| `np.transpose()` | Transpose of matrix |
| `np.sort()` | Sorting array |

---

## Import and Usage

In [2]:

# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((2,3))
ones = np.ones((3,3))
identity = np.eye(4)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

# Range and linspace
arange_arr = np.arange(0, 10, 3)
linspace_arr = np.linspace(0, 1, 5)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(2,3)
print("Random Array:\n", rand_arr)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Arange: [0 3 6 9]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random Array:
 [[0.54308422 0.97225393 0.12093563]
 [0.89955551 0.93935656 0.07139655]]


## Example

In [3]:
# Example 1: Reshape and Transpose
matrix = np.arange(1, 13).reshape(2,6)
print("Matrix:\n", matrix)
print("Transpose:\n", matrix.T)

# Example 2: Mathematical operations
arr = np.array([10, 20, 30, 40])
print("Original Array:", arr)
print("Array + 5:", arr + 5)
print("Array squared:", arr ** 2)

# Example 3: Aggregate Functions
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

# Example 4: Matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("Matrix Multiplication:\n", np.dot(A,B))

# Example 5: Sorting
unsorted = np.array([3,1,4,1,5,9])
print("Sorted Array:", np.sort(unsorted))


Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Transpose:
 [[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]
Original Array: [10 20 30 40]
Array + 5: [15 25 35 45]
Array squared: [ 100  400  900 1600]
Sum: 100
Mean: 25.0
Standard Deviation: 11.180339887498949
Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [1 1 3 4 5 9]
